version: "3"
services:
  app:
    build: .
    ports:
      - 8084:80
    volumes:
      - .:/var/www/html
    links:
      - mysql

  mysql:
    image: mysql:5.7.28
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33065:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_ROOT_DATABASE: study_php
